env:
  global:
    - CC_TEST_REPORTER_ID=f67fe1eb15b21f989e1dd831ceab85a652402c7fcdb3571292f65b8561d4e314
language: ruby
rvm:
 - 2.5.1
services:
 - redis-server
 - postgresql
before_install:
 - gem update --system
 - gem install bundler:1.17.3
 - gem install bundler
cache: bundler
before_script:
 - RAILS_ENV=test bundle exec rake db:create
 - RAILS_ENV=test bundle exec rake db:migrate
script:
 - bundle exec rspec
after_script:
 - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT