default: &default
  adapter: postgresql
  encoding: utf8

development:
  <<: *default
  pool: 20
  timeout: 5000
  username: postgres
  password: postgres
  host: localhost
  database: cartolapgeapi_development

test:
  <<: *default
  username: postgres
  password: postgres
  host: localhost
  database: cartolapgeapi_test

production:
  <<: *default
  database: cartolapgeapi_production
  username: cartolapgeapi
  password: <%= ENV['RUBY-CARTOLAPGEAPI_DATABASE_PASSWORD'] %>
